spring:
  application:
    name: spring-reactive-demo
  
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

server:
  port: 8080

logging:
  level:
    com.interview: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG